import type { GeneratedPlan } from "./schema";

export const EXAMPLE_IDEA =
  "An AI assistant for staffing agencies that helps dispatchers fill customer orders with temp workers, checks pay rules from collective agreements, and drafts offers to workers.";

// Hand-written example so the board works without an API call.
export const EXAMPLE_PLAN: GeneratedPlan = {
  appName: "Dispatcher Copilot",
  features: [
    {
      name: "Order inbox from email",
      description: "Turns a customer's free-text email into a structured order: role, headcount, shift, location, start date.",
      needsLLM: true,
      callsPerUserMonth: 60,
      inputTokens: 1800,
      outputTokens: 300,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Pure extraction into fixed fields; Haiku is accurate and cheap enough.",
    },
    {
      name: "Worker matching",
      description: "Ranks available workers for an order by skills, licences, distance and availability.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Filters and scoring over database fields; no language needed.",
    },
    {
      name: "Pay rule calculator",
      description: "Works out pay group, sector surcharge and the Equal Pay deadline for each placement.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Fixed legal rules belong in tested code, not in a model.",
    },
    {
      name: "Ask the agreement",
      description: "Answers dispatcher questions about collective agreements and temp-work law, citing the exact passage.",
      needsLLM: true,
      callsPerUserMonth: 40,
      inputTokens: 12000,
      outputTokens: 600,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-sonnet-5-5",
      rationale: "Needs careful reading of long legal text with citations; the agreement text caches well.",
    },
    {
      name: "Explain a warning",
      description: "Explains in plain words why a placement is flagged, e.g. the 18-month limit is close.",
      needsLLM: true,
      callsPerUserMonth: 30,
      inputTokens: 2500,
      outputTokens: 200,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Short explanation of an already-computed rule.",
    },
    {
      name: "Offer drafting",
      description: "Drafts a personal job offer for each matched worker, ready to send by SMS or email.",
      needsLLM: true,
      callsPerUserMonth: 120,
      inputTokens: 1500,
      outputTokens: 250,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Short templated writing; tone matters more than reasoning.",
    },
    {
      name: "Shift planning agent",
      description: "Plans a full week of shifts across several customers, resolving clashes and suggesting swaps.",
      needsLLM: true,
      callsPerUserMonth: 8,
      inputTokens: 30000,
      outputTokens: 4000,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-opus-5-5",
      rationale: "Multi-step planning with many constraints; worth the stronger model.",
    },
    {
      name: "Weekly customer report",
      description: "Summarises fill rate, no-shows and hours per customer as a short weekly email.",
      needsLLM: true,
      callsPerUserMonth: 4,
      inputTokens: 8000,
      outputTokens: 800,
      cacheable: false,
      batchable: true,
      suggestedModel: "claude-sonnet-5-5",
      rationale: "Summarising numbers into prose; nobody needs it instantly, so batch it.",
    },
    {
      name: "Timesheet anomaly check",
      description: "Flags unusual timesheets (overtime spikes, missing breaks) before payroll runs.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Threshold rules catch these reliably.",
    },
    {
      name: "Candidate CV parsing",
      description: "Reads uploaded CVs and fills the worker profile: skills, licences, languages, experience.",
      needsLLM: true,
      callsPerUserMonth: 25,
      inputTokens: 3500,
      outputTokens: 500,
      cacheable: true,
      batchable: true,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Structured extraction; can run in the background overnight.",
    },
    {
      name: "Dashboard & KPIs",
      description: "Open orders, fill rate, margin per placement and upcoming deadlines at a glance.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Database queries and charts.",
    },
    {
      name: "Dispatcher chat assistant",
      description: "A general chat that can look up orders, workers and rules and take simple actions.",
      needsLLM: true,
      callsPerUserMonth: 150,
      inputTokens: 6000,
      outputTokens: 400,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-sonnet-5-5",
      rationale: "Tool-using agent with frequent use; Sonnet balances quality and cost.",
    },
  ],
};
