import type { GeneratedPlan } from "./schema";

export const EXAMPLE_BRIEF = [
  { label: "Who pays", text: "Staffing agencies, per dispatcher seat, as an add-on to their staffing software." },
  {
    label: "The problem today",
    text: "Dispatchers lose hours a day filling customer orders by phone and checking pay rules from collective agreements by hand. Mistakes mean fines or back-pay.",
  },
  {
    label: "What the product changes",
    text: "An AI assistant reads incoming orders, suggests suitable temp workers, checks the pay rules and drafts offers. The dispatcher approves each step.",
  },
];

// Hand-written example so the board works without an API call.
export const EXAMPLE_PLAN: GeneratedPlan = {
  appName: "Dispatcher Copilot",
  features: [
    {
      name: "Order inbox from email",
      description: "Turns a customer's free-text email into a structured order: role, headcount, shift, location, start date.",
      needsLLM: true,
      callsPerUserMonth: 60,
      inputTokens: 1800,
      outputTokens: 300,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Pure extraction into fixed fields; Haiku is accurate and cheap enough.",
      customerValue: 4,
      valueReason: "Saves dispatchers ~5 minutes per order and no order gets lost in the inbox.",
      riskIfWrong: "medium",
      riskNote: "A wrong start date or headcount means an unfilled shift; dispatcher confirms before saving.",
    },
    {
      name: "Worker matching",
      description: "Ranks available workers for an order by skills, licences, distance and availability.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Filters and scoring over database fields; no language needed.",
      customerValue: 5,
      valueReason: "Fills shifts faster: the core job the agency is paid for.",
      riskIfWrong: "medium",
      riskNote: "A bad match wastes a placement; rules are tested code and the dispatcher picks.",
    },
    {
      name: "Pay rule calculator",
      description: "Works out pay group, sector surcharge and the Equal Pay deadline for each placement.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Fixed legal rules belong in tested code, not in a model.",
      customerValue: 5,
      valueReason: "Avoids underpaying workers, which risks fines and back-payments.",
      riskIfWrong: "high",
      riskNote: "Wrong pay breaks the law; keep it as tested rules, never an LLM guess.",
    },
    {
      name: "Ask the agreement",
      description: "Answers dispatcher questions about collective agreements and temp-work law, citing the exact passage.",
      needsLLM: true,
      callsPerUserMonth: 40,
      inputTokens: 12000,
      outputTokens: 600,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-sonnet-5-5",
      rationale: "Needs careful reading of long legal text with citations; the agreement text caches well.",
      customerValue: 4,
      valueReason: "Answers compliance questions in seconds instead of calling the legal team.",
      riskIfWrong: "high",
      riskNote: "A wrong legal answer can cause underpayment; always cite the passage and eval on real questions.",
    },
    {
      name: "Explain a warning",
      description: "Explains in plain words why a placement is flagged, e.g. the 18-month limit is close.",
      needsLLM: true,
      callsPerUserMonth: 30,
      inputTokens: 2500,
      outputTokens: 200,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Short explanation of an already-computed rule.",
      customerValue: 3,
      valueReason: "Dispatchers understand and fix flags without training.",
      riskIfWrong: "medium",
      riskNote: "A misleading explanation could hide a real issue; the rule itself stays in code.",
    },
    {
      name: "Offer drafting",
      description: "Drafts a personal job offer for each matched worker, ready to send by SMS or email.",
      needsLLM: true,
      callsPerUserMonth: 120,
      inputTokens: 1500,
      outputTokens: 250,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Short templated writing; tone matters more than reasoning.",
      customerValue: 4,
      valueReason: "Workers get offers minutes after an order, before competitors call them.",
      riskIfWrong: "medium",
      riskNote: "A wrong shift time in an offer causes no-shows; fill facts from data, let the LLM write only the wording.",
    },
    {
      name: "Shift planning agent",
      description: "Plans a full week of shifts across several customers, resolving clashes and suggesting swaps.",
      needsLLM: true,
      callsPerUserMonth: 8,
      inputTokens: 30000,
      outputTokens: 4000,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-opus-5-5",
      rationale: "Multi-step planning with many constraints; worth the stronger model.",
      customerValue: 5,
      valueReason: "Plans a week of shifts in minutes instead of hours.",
      riskIfWrong: "high",
      riskNote: "A bad plan breaks working-time law or leaves shifts empty; human approves every plan.",
    },
    {
      name: "Weekly customer report",
      description: "Summarises fill rate, no-shows and hours per customer as a short weekly email.",
      needsLLM: true,
      callsPerUserMonth: 4,
      inputTokens: 8000,
      outputTokens: 800,
      cacheable: false,
      batchable: true,
      suggestedModel: "claude-sonnet-5-5",
      rationale: "Summarising numbers into prose; nobody needs it instantly, so batch it.",
      customerValue: 2,
      valueReason: "Nice for account managers, but customers rarely buy for it.",
      riskIfWrong: "low",
      riskNote: "A clumsy summary is embarrassing, not harmful; numbers come from the database.",
    },
    {
      name: "Timesheet anomaly check",
      description: "Flags unusual timesheets (overtime spikes, missing breaks) before payroll runs.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Threshold rules catch these reliably.",
      customerValue: 4,
      valueReason: "Catches payroll errors before they cost money.",
      riskIfWrong: "medium",
      riskNote: "Missed anomalies reach payroll; tune thresholds with past data.",
    },
    {
      name: "Candidate CV parsing",
      description: "Reads uploaded CVs and fills the worker profile: skills, licences, languages, experience.",
      needsLLM: true,
      callsPerUserMonth: 25,
      inputTokens: 3500,
      outputTokens: 500,
      cacheable: true,
      batchable: true,
      suggestedModel: "claude-haiku-4-5",
      rationale: "Structured extraction; can run in the background overnight.",
      customerValue: 3,
      valueReason: "Profiles are complete without manual typing.",
      riskIfWrong: "low",
      riskNote: "A missed skill costs a match; the worker confirms their profile.",
    },
    {
      name: "Dashboard & KPIs",
      description: "Open orders, fill rate, margin per placement and upcoming deadlines at a glance.",
      needsLLM: false,
      callsPerUserMonth: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheable: false,
      batchable: false,
      suggestedModel: "none",
      rationale: "Database queries and charts.",
      customerValue: 3,
      valueReason: "Managers see fill rate and margin at a glance.",
      riskIfWrong: "low",
      riskNote: "Plain queries; test them like any report.",
    },
    {
      name: "Dispatcher chat assistant",
      description: "A general chat that can look up orders, workers and rules and take simple actions.",
      needsLLM: true,
      callsPerUserMonth: 150,
      inputTokens: 6000,
      outputTokens: 400,
      cacheable: true,
      batchable: false,
      suggestedModel: "claude-sonnet-5-5",
      rationale: "Tool-using agent with frequent use; Sonnet balances quality and cost.",
      customerValue: 2,
      valueReason: "Handy, but overlaps with the focused features above.",
      riskIfWrong: "medium",
      riskNote: "Open-ended chat can take wrong actions; limit tools and require confirmation.",
    },
  ],
};
